INSERT INTO users (username, email, password, activated) VALUES ('marko', 'marko@example.com', 'password123', true);
INSERT INTO users (username, email, password, activated) VALUES ('milan', 'milan@example.com', 'password456', true);
INSERT INTO users (username, email, password, activated) VALUES ('ivana', 'ivana@example.com', 'password789', false);
INSERT INTO users (username, email, password, activated) VALUES ('bojan', 'bojan@example.com', 'bojanpass', true);
INSERT INTO users (username, email, password, activated) VALUES ('pera', 'pera@example.com', 'perapass', false);
INSERT INTO users (username, email, password, activated) VALUES ('zoran', 'zoran@example.com', 'zoranpass', true);
INSERT INTO users (username, email, password, activated) VALUES ('bojana', 'bojana@example.com', 'bojanapass', false);
INSERT INTO users (username, email, password, activated) VALUES ('milana', 'milana@example.com', 'milanapass', true);
INSERT INTO users (username, email, password, activated) VALUES ('jovana', 'jovana@example.com', 'jovanapass', false);
